### ISSUE TITLE
Not really an issue.

### ISSUE THREAD

**Issue by pyeatt** [matrix-io/xc3sprog#15]
Hi, Thanks very much for this great piece of software!  I had a few minor problems installing it on Ubuntu Intel. I documented the steps at: https://www.mcs.sdsmt.edu/lpyeatt/courses/ceng342/xc3sprog.txt so feel free to add that to your README.md or whatever.

The only real issue was adding some libraries to the link step.  Other than that, it was just making sure all the dependencies were there.  Thanks again for the great code!

**Comment by eljuguetero** [comment]
Thank you
