### ISSUE TITLE
SYSFS_GPIO Removed?

### ISSUE THREAD

**Issue by terriblefire** [matrix-io/xc3sprog#18]
In commit 87ea51d465777039d5c6931d268a08b391922ce1 you seemed to remove SYSFS_GPIO cable support... Why? This worked amazingly for most of my customers in using a Pi to update the firmwares on their Amiga accelerators. 

Is there an alternative? If not please restore this cable. It was awesome

**Comment by terriblefire** [comment]
Ah its just been renamed... weird but ok.

**Comment by TheBilgeRat** [comment]
I can't for the life of me find out what it was renamed to.
