### ISSUE TITLE
GPIO Pin Change 

### ISSUE THREAD

**Issue by silverfox0786** [matrix-io/xc3sprog#22]
before i was able to change Pi GPIO pin-outs from sysfs.cpp. can you tell me how you do it now as i cant find it. since the changes you have made for Pi-4.

Thanks

**Comment by eljuguetero** [comment]
_wiringpi_  has been deprecated and support for RPi4 has errors, for MATRIX boards we add support for 4 cables:

https://github.com/matrix-io/xc3sprog/blob/master/cablelist.txt#L46

- _sysfsgpio_creator_: based on GPIO sysfs, compatible with RPi3 and RPi4 (**very slow**) 
- _sysfsgpio_voice_: based on GPIO sysfs, compatible with RPi3 and RPi4 (**very slow**) 
- _matrix_creator_: based in wiringpi,  not compatible with RPi4 (**fast**)
- _matrix_voice_: based in wiringpi,  not compatible with RPi4 (**fast**)

Source code for GPIO sysfs:

- [sysfs.h](https://github.com/matrix-io/xc3sprog/blob/master/sysfs.h)
- [sysfs.cpp](https://github.com/matrix-io/xc3sprog/blob/master/sysfs.cpp)
- [sysfscreator.h](https://github.com/matrix-io/xc3sprog/blob/master/sysfscreator.h)
- [sysfscreator.cpp](https://github.com/matrix-io/xc3sprog/blob/master/sysfscreator.cpp)
- [sysfsvoice.h](https://github.com/matrix-io/xc3sprog/blob/master/sysfsvoice.h)
- [sysfsvoice.cpp](https://github.com/matrix-io/xc3sprog/blob/master/sysfsvoice.cpp)

**Comment by eljuguetero** [comment]
@silverfox0786 

please check here:
https://github.com/matrix-io/xc3sprog/blob/master/sysfs.h#L8
https://github.com/matrix-io/xc3sprog/blob/master/sysfscreator.cpp#L4
