### ISSUE TITLE
fatal error: wiringPi.h: No such file or directory

### ISSUE THREAD

**Issue by aep** [matrix-io/xc3sprog#24]
master doesn't compile out of the box. google leads me to believe this is

http://wiringpi.com/ ?

but the readme doesnt mention that, and i'm super confused why this project is related to raspberry pi at all.

**Comment by zackpi** [comment]
having the same issue. Did you have any luck after adding wiringPi.h?

**Comment by zackpi** [comment]
seems like wiringPi is no longer officially supported. I'm beginning to think that xc3sprog is not either, since it seems to use several deprecated systems. Is there an alternative open-source project for programming Arty 7 boards?

**Comment by aep** [comment]
nop, openocd works fine for me fwiw

**Comment by pcwwgkg** [comment]
I don't think they are still maintaining this project. There are two existing PRs trying to resolve this. I can confirm they work.

**Comment by AlieGG** [comment]
@pcwwgkg Thanks for pointing that out to us. I'm having our engineers test the PRs so we can merge them.

**Comment by AlieGG** [comment]
Ok we have merged this PR which gets around wiringpi. https://github.com/matrix-io/xc3sprog/pull/20
