### ISSUE TITLE
Feature request: Override write protection during erase

### ISSUE THREAD

**Issue by tkurbad** [matrix-io/xc3sprog#37]
Hi,

IMPACT has an option to do a full erase of write protected devices.

Could this be implemented (perhaps using a command line switch like -f(force) )

Thanks,
Torsten

**Comment by DanielO** [comment]
How does it fail? Looking at the code and platform flash docs (xapp972.pdf) I think it would work already because it sends XSC_UNLOCK.

**Comment by tkurbad** [comment]
It tries to erase and then says: "Device still not empty fe" or similar. Once unlocked using IMPACT, the chip can be written and erased by xc3sprog.

**Comment by DanielO** [comment]
What device is it and how do you write protect it in the first place?

**Comment by DanielO** [comment]
What device is it and how do you write protect it in the first place?

**Comment by tkurbad** [comment]
It was a bunch of XC95288XL-10TQ144C I bought used on eBay.
They were seemingly desoldered from some commercial product and had color markings on top.

They came read/write protected. I don't know how this was done, but only IMPACT could erase them after setting a "override write protection" flag in the respective dialog. (I can make a screenshot later)

**Comment by DanielO** [comment]
OK I see.
I had a look but the XC5900 data sheet does not specify how to unlock them :(

I think the only way would be to analyse what Impact does (or find some code which has already got the secret sauce).

Unfortunately that's a bit beyond me.

**Comment by tkurbad** [comment]
No problem. I never encountered this before or after, so I think it's a corner case in daily use anyway.

If I ever get around to hooking up a logic analyzer to the JTAG I could compare the erase cycle with and without the flag set - in the hopes that this sheds some light on the matter. For now, let's close this.

Thank you for looking into it!
